Update endpoint Judge.
MinervaLMS/judge-api pull request #16
Opened 2023-09-29 05:28 UTC by dmolinat

* 50 Cases, passed.
* New pytest.fixture.
* Documentation in the next days in CODA.
* Add new covered exception when "ans - Verdict of judge" is empty.

2023-09-30 16:33 UTC, zabaldo requested changes
- Falta revisar los test a cargo de @chenaor 
- El veredicto no funciona del todo bien, hay casos que deberia dar MLE pero no retorna eso

2023-09-30 16:33 UTC, zabaldo commented on app/problem/file_creator.py
> +            zip(self.input_data, self.output_data), start=0
Es un cambio innecesario ademas de no debería ir en este commit

2023-09-30 16:33 UTC, zabaldo commented on app/problem/file_creator.py
> +        for i in range(0, len(self.input_data)):
Es un cambio innecesario ademas de no debería ir en este commit

2023-09-30 16:33 UTC, zabaldo commented on app/problem/file_creator.py
> +            for i in range(0, len(self.input_data)):
Es un cambio innecesario ademas de no debería ir en este commit

2023-09-30 16:33 UTC, zabaldo commented on app/problem/file_creator.py
> -            yaml.dump(yml_data, yml_file, default_flow_style=None)
Es un cambio innecesario ademas de no debería ir en este commit

2023-09-30 16:33 UTC, zabaldo commented on app/middleware/request_validations.py
> +            raise RequestFormatError("memory_limit", "Invalid memory limit provided.")
Estos limites estan mal y faltarían los limites minimos

2023-09-30 16:33 UTC, zabaldo commented on app/executor/executor.py
> +        """Return a resume of veredicts as a dict"""
Esto no debería estar separado en dos lineas con dos """

2023-09-30 16:33 UTC, zabaldo commented on app/executor/executor.py
> +
Nunca se usa

2023-09-30 16:33 UTC, zabaldo commented on app/middleware/request_validations.py
> +        if (self.time_limit > 10000):
falta limite negativo

2023-09-30 16:33 UTC, zabaldo commented on app/problem/views.py
> +    return jsonify({"message": "Problem created successfully."}), 200
Es un cambio innecesario ademas de no debería ir en este commit

2023-09-30 16:33 UTC, zabaldo commented on app/utils/constants.py
> +PROBLEMS_FOLDER = "/../mnt/problems/"
Genera problemas por permisos de usuario
Es un cambio innecesario ademas de no debería ir en este commit

2023-10-07 16:58 UTC, zabaldo commented
@dmolinat Debes hacer los cambios que hay endientes para pasar el MR y tener listo lo para presentar el lunes 9 de octubre

2023-10-07 17:45 UTC, dmolinat commented on app/executor/executor.py
> +
Se usa en las pruebas: coverage run -m pytest

2023-10-07 17:53 UTC, dmolinat commented on app/middleware/request_validations.py
> +            raise RequestFormatError("memory_limit", "Invalid memory limit provided.")
Tener presente que el juez, para realizar un print("Hola mundo"), gasta 8000 kb aproximadamente, entonces toca revisar eso primero, por ahora se agregará el limite inferior con el mismo límite superior hasta que se sepa qué se hará con ello.

2023-10-09 03:55 UTC, Tholes approved these changes

2023-10-09 03:56 UTC, zabaldo approved these changes

2023-10-09 03:57 UTC, merged